### PR TITLE
add --force flag for overriding an existing script entry

### PR DESCRIPTION
**Pull request by npup**
Hi!
Found (and used) your script-adder (hisssssss!!!!) today, and after a while i started looking for a way to replace existing script entries. Maybe this is useful for you?

### CODE REVIEW

**Comment by coleww** [comment]
thanks! before i merge/publish this, could you update the README.md to document this option in the CLI/API sections, and fix the formatting stuff that travis caught?

**Comment by npup** [comment]
oh schucks i forgot the readme. 
sure, later tonight then!

**Comment by npup** [comment]
I think this became mergeable with that?

**Comment by coleww** [comment]
cool thanks! will publish a new version soon

**Pull request merged**
